CREATE TABLE labelled_protocol (
labelled_protocol_id integer NULL,
labelled_protocol_idname VARCHAR (50) NULL,
labelled_protocol_name VARCHAR (100) NULL,
labelling_type VARCHAR (10) NOT NULL,
label_name VARCHAR (50) NULL,
amplification VARCHAR (10) NOT NULL,
molecule_type VARCHAR (20) NOT NULL,
concentration_value real NOT NULL,
concentration_unit VARCHAR (10) NOT NULL,
concentration_db real NOT NULL,
quantity_value real NOT NULL,
quantity_unit VARCHAR (10) NOT NULL,
quantity_db real NOT NULL,
note VARCHAR (4000) NOT NULL,
protocol_id integer NOT NULL,
protocol_id2 integer NOT NULL,
user_id integer NOT NULL,
submission_date date NOT NULL );
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (5,"P35E50L5","Indirect_labelling_GFE","indirect","Cy3 and Cy5","no","RNAm","None","None","None",1.0,"ug",1.0,"Extraction of polyA+RNA from total RNA samples and labelling of 0.5 to 1 ug. ",17,"None",10,"2005-04-06");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (8,"P212E326L8","AFFY_NuGen","indirect","Biotin","yes","total RNA","None","None","None","None","None","None","None",10125,"None",7,"2010-01-13");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (6,"P55E86L6","indirect-labelling-protocol-M4","indirect","Alexa and Cy5 and Cy3","yes","RNAa",30.0,"pM",30000000.0,5.0,"ug",5.0,"5(u)g of aRNA are reverse transcript with superscript2 which incorpore amino-allyl dUTP. amino allyled cDNA are then coupled with the succimidyl ester dye (cy5, cy3 or Alexa 594)",74,"None",44,"2005-12-22");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (7,"P94E146L7","ChIP-chip: PCR and direct labelling","direct","Cy3 and Cy5","yes","DNA","None","None","None","None","None","None","None",122,123,133,"2006-11-08");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (10,"P237E360L10","Affy_WT","indirect","Biotin","yes","ssDNA","None","None","None",5.5,"ug",5.5,"None",10163,"None",7,"2010-06-18");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (3,"P72E106L3","labelling_protocol","direct","Cy3 and Cy5","yes","aRNA","None","None","None",5.0,"ug",5.0,"None",9,"None",5,"2008-09-11");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (9,"P260E416L9","DNA_labeling_Affy_protocol","indirect","Biotin","no","DNA","None","None","None","None","None","None","None",10148,"None",133,"2010-10-01");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (11,"P257E400L11","Nimblegen ChIP-chip","indirect","Cy3 and Cy5","yes","DNA","None","None","None","None","None","None","None",10190,10191,133,"2010-09-14");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (12,"P260E416L12","CGH_labelling","direct","Cy3 and Cy5","no","DNA","None","None","None","None","None","None","None","None",123,133,"2010-10-01");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (4,"P331E503L4","Affymetrix","direct","Biotin","yes","cRNA","None","None","None",20.0,"ug",20.0,"None",11,"None",238,"2013-02-08");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (13,"P332E504L13","OVATION ","direct","Biotin","yes","total RNA","None","None","None",50.0,"ng",0.05,"None",10125,"None",238,"2013-02-14");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (14,"P332E504L14","amplif","direct","Biotin","yes","total RNA",150.0,"pM",150000000.0,"None","None","None","None",10125,"None",238,"2013-03-28");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (15,"P336E507L15"," WTA2 - KitTransPlex Complete Whole Transcripotme Amplification","direct","Cy3 and Cy5","yes","total RNA","None","None","None","None","None","None","None",10280,"None",174,"2013-04-10");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (16,"P356E529L16","AMPLIF_VITIS","indirect","Cy3 and Cy5","yes","total RNA",100.0,"nM",100000.0,"None","None","None","None",9,"None",238,"2013-11-26");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (17,"P384E561L17","Agilent_GeneExpression_TwoColor","direct","Cy3 and Cy5","yes","aRNA","None","None","None",200.0,"nmol",0.2,"None","None","None",0,"2015-01-27");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (18,"P411E588L18","AGILENT 1/2 vol_ Low Input Quick Amp Labeling ","direct","Cy3 and Cy5","yes","total RNA","None","None","None","None","None","None","None","None","None",335,"2016-05-24");
INSERT INTO labelled_protocol (labelled_protocol_id,labelled_protocol_idname,labelled_protocol_name,labelling_type,label_name,amplification,molecule_type,concentration_value,concentration_unit,concentration_db,quantity_value,quantity_unit,quantity_db,note,protocol_id,protocol_id2,user_id,submission_date) VALUES (19,"P371E545L19","AMBION amplification and labelling Cy3/Cy5","direct","Cy3 and Cy5","yes","total RNA","None","None","None","None","None","None","Kit Ambion: MessageAmpII aRNA Amplification #1751Labelling by retro-transcription des aRNAPurification Kit Qiaquick QIAGEN Cat.N°28106.","None","None",335,"2018-09-20");
