CREATE TABLE scananalysis_protocol (
scananalysis_protocol_id integer NULL,
scananalysis_protocol_idname VARCHAR (50) NULL,
scananalysis_protocol_name VARCHAR (100) NULL,
pmt_voltage_1 VARCHAR (10) NOT NULL,
pmt_voltage_2 VARCHAR (10) NOT NULL,
pmt_voltage_3 VARCHAR (10) NOT NULL,
laser_power VARCHAR (50) NOT NULL,
laser_power_2 VARCHAR (50) NOT NULL,
laser_power_3 VARCHAR (50) NOT NULL,
method_analysis VARCHAR (100) NOT NULL,
software_analysis VARCHAR (100) NOT NULL,
platform_name VARCHAR (100) NOT NULL,
protocol_id integer NOT NULL,
user_id integer NOT NULL,
submission_date date NOT NULL,
precision VARCHAR (10) NOT NULL );
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (2,"P24E36ScanProto2","Scan700/650","700V","650V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA","None",0,"2005-01-24","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (3,"P30E42ScanProto3","Scan680/650","650V","680V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA","None",1,"2005-03-15","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (1,"P30E42ScanProto1","Scan650/650","650V","650V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA","None",1,"2005-03-15","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (4,"P34E47ScanProto4","Scan650/610","650V","610V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA","None",0,"2005-03-30","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (5,"P35E50ScanProto5","scan600/600","600V","600V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","Chromochip","None",10,"2005-04-08","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (6,"P35E50ScanProto6","scan-650/650","650V","650V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","Chromochip","None",10,"2005-04-08","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (7,"P14E59ScanProto7","Scan650/620","650V","620V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA",10000,0,"2005-06-20","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (8,"P35E50ScanProto8","Scan700/650","650V","700V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","Chromochip",10000,10,"2005-09-21","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (9,"P35E50ScanProto9","Scan710/650","650V","710V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","Chromochip",10000,10,"2005-09-21","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (10,"P55E86ScanProto10","M4-scan-protocol","526V","605V","650","50%","50%","100%","adaptative","GenePix Pro 3.0","CATMA",10000,44,"2005-12-22","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (11,"P81E125ScanProto11","SCAN_CAGE","450V","450V","None","100%","100%","None","None","GenePix Pro 3.0","CAGE",102,9,"2006-06-22","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (12,"P73E115ScanProto12","4200A_500-30","500V","500V","None","30%","30%","None","fixed circle","GenePix Pro 6.0","CATMA",10000,1,"2006-07-06","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (13,"P66E100ScanProto13","scan 600-570","600V","570V","None","100%","100%","None","None","GenePix Pro 3.0","Chromochip",10000,95,"2006-07-13","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (14,"P94E146ScanProto14","ChIP-chip_GFE","550V","600V","None","100%","100%","None","None","GenePix Pro 3.0","Chromochip",10000,133,"2006-11-10","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (15,"P95E147ScanProto15","affy_scan_protocol","650V","None","None","1","None","None","None","GCOS","Affymetrix",10000,7,"2006-12-06","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (16,"P28E40ScanProto16","Scan650/700","650V","700V","None","100%","100%","None","None","GenePix Pro 3.0","CATMA",10000,5,"2006-12-28","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (17,"P105E160ScanProto17","Scan770/600","600V","770V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA",10000,149,"2007-03-22","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (18,"P108E166ScanProto18","Scan750-620","620V","750V","None","100%","100%","None","None","GenePix Pro 6.0","CATMA",10000,95,"2007-03-29","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (19,"P100E152ScanProto19","Scan650/520","650V","520V","None","100%","100%","None","fixed circle","GenePix Pro 3.0","CATMA",10000,0,"2007-04-11","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (20,"P109E167ScanProto20","Scan800/650","650V","800V","None","100%","100%","None","None","GenePix Pro 6.0","CATMA",10000,95,"2007-04-12","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (21,"P70E187ScanProto21","ScanCEA700/530","530V","700V","None","100%","100%","None","None","GenePix Pro 3.0","CATMA",10000,65,"2007-09-19","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (22,"P128E189ScanProto22","Scan650-33","650V","650V","None","33%","33%","None","None","GenePix Pro 3.0","CATMA",10000,65,"2007-10-10","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (23,"P125E184ScanProto23","Multiplexage","500V","500V","620","30%","30%","30%","None","GenePix Pro 6.0","CATMA",10000,65,"2007-10-30","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (24,"P129E190ScanProto24","Scan680/680(loanedscan)","680V","680V","None","33%","33%","None","fixed circle","GenePix Pro 3.0","CATMA",10000,0,"2007-10-30","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (25,"P108E166ScanProto25","4200A_500-30_500-35","500V","500V","None","35%","30%","None","None","GenePix Pro 3.0","CATMA",10000,95,"2007-12-19","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (26,"P113E216ScanProto26","4200A_460-30_460-35","460V","460V","None","35%","30%","None","None","GenePix Pro 3.0","CATMA",0,95,"2008-05-20","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (27,"P125E223ScanProto27","4200A-460_30-460_35","460V","460V","None","35%","30%","None","None","GenePix Pro 3.0","SAP",0,95,"2008-05-30","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (30,"P229E351ScanProto30","InnoScan900_3µ","650V","700V","None","5%","5%","None","None","InnoScan900_MAPIX","NimbleGen",0,7,"2010-05-05","3");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (28,"P125E252ScanProto28","Multiplexage2 - 4200A","480","500","640","30%","35%","35%","None","GenePix Pro 4.0","CATMA",0,65,"2008-09-03","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (29,"P195E300ScanProto29","4200A_480-30_480-35","480V","480V","None","35%","30%","None","None","GenePix Pro 3.0","CATMA",0,174,"2010-02-09","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (31,"P260E417ScanProto31","Nimblegen_Scan","650V","700V","None","100%","100%","None","None","NimbleGen","NimbleGen",10193,133,"2010-10-01","None");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (32,"P309E480ScanProto32","InnoScan900_2µ","480V","480V","None","35%","30%","None","None","Mapix","NimbleGen",0,0,"2012-06-21","2µ");
INSERT INTO scananalysis_protocol (scananalysis_protocol_id,scananalysis_protocol_idname,scananalysis_protocol_name,pmt_voltage_1,pmt_voltage_2,pmt_voltage_3,laser_power,laser_power_2,laser_power_3,method_analysis,software_analysis,platform_name,protocol_id,user_id,submission_date,precision) VALUES (33,"P377E553ScanProto33","AGILENT_scan protocol","650V","700V","None","50%","45%","None","None","GenePix Pro 3.0","Agilent",0,335,"2014-06-13","2µ");
