CREATE TABLE ecotype (
ecotype_id integer NULL,
ecotype_name VARCHAR (50) NULL );
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (1,"columbia");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (2,"landsberg erecta");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (3,"wassilewskija");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (4,"burren");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (5,"ril bay-0 x shahdara");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (20,"col-0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (34,"ril ");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (32,"halophyla");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (9,"shahdara");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (10,"cv hanna");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (11,"cms-line");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (12,"restored line 46");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (33,"jemalong");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (14,"pactol");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (30,"col-24");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (21,"f252");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (22,"indica, japonica");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (18,"synthetic tetraploid ");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (19,"cape verde islands");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (35,"ril cvi x col-0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (36,"ril bur x col-0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (25,"col x ws");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (26,"41528 population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (37,"col-8");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (38,"nipponbare");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (39,"cvi");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (40,"a17");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (27,"pn40024");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (41,"bm4");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (8,"bay-0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (15,"restored line for ppr");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (13,"cv hanna + A. thaliana chr 3");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (28,"colombia x landsberg erecta");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (29,"bologna-1");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (42,"colxcvi hybrids");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (23,"sbsp durum");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (43,"c24");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (44,"nossen");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (45,"a17xf83005.5");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (46,"ir64");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (47,"irbb4");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (48,"hirsutum");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (49,"cv jemalong");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (50,"distachyon");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (51,"columbia_0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (52,"columbia-0");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (53,"hybrid");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (54,"bd21");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (55,"oleracea");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (56,"pinot noir");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (57,"serix babax rils");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (58,"r108");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (59,"163av");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (60,"darmor");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (61,"yudal");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (62,"caméor");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (63,"cervil");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (64,"levovil");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (65,"nodules");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (66,"Physcomitrella patens");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (67,"columbia x wassilewskija");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (68,"Maize");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (69,"vitreous endosperm from flint maize");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (70,"floury endosperm from flint maize");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (71,"vitreous endosperm from dent maize");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (72,"floury endosperm from dent maize");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (73,"adour population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (74,"dranse population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (75,"loire population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (76,"ramieres population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (77,"rhin population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (78,"ticino population");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (79,"cv 717 1b4");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (80,"brachypodium");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (81,"b73");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (82,"gd");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (83,"chardonnay");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (84,"mesnil-soleil");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (85,"boigneville");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (86,"poncin");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (87,"villeneuve");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (88,"kayl");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (89,"hirtzbach");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (90,"evosges");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (91,"levier");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (92,"Barley_Hordeum vulgare");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (93,"barley, nur variety");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (94,"Brassica Oleracea");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (95,"cs");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (96,"m");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (97,"nar+ alfalfa");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (98,"lycopersicon esculentum");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (99,"plaisance");
INSERT INTO ecotype (ecotype_id,ecotype_name) VALUES (100,"brassica napus l. var citizzen");
