CREATE TABLE organism (
organism_id integer NULL,
organism_name VARCHAR (50) NULL );
INSERT INTO organism (organism_id,organism_name) VALUES (1,"Arabidopsis thaliana");
INSERT INTO organism (organism_id,organism_name) VALUES (29,"Alopecurus myosuroides ");
INSERT INTO organism (organism_id,organism_name) VALUES (3,"Brassica napus");
INSERT INTO organism (organism_id,organism_name) VALUES (4,"Triticum aestivum");
INSERT INTO organism (organism_id,organism_name) VALUES (5,"Triticum monococcum");
INSERT INTO organism (organism_id,organism_name) VALUES (6,"Triticum turgidum");
INSERT INTO organism (organism_id,organism_name) VALUES (9,"Triticum urartu x Aegilops tauschii");
INSERT INTO organism (organism_id,organism_name) VALUES (8,"Aegilops tauschii");
INSERT INTO organism (organism_id,organism_name) VALUES (2,"Triticum urartu");
INSERT INTO organism (organism_id,organism_name) VALUES (28,"Triticum turgidum x Aegilops tauschii");
INSERT INTO organism (organism_id,organism_name) VALUES (18,"Populus tremula x Populus alba");
INSERT INTO organism (organism_id,organism_name) VALUES (12,"Zea mays");
INSERT INTO organism (organism_id,organism_name) VALUES (21,"Populus deltoides x Populus nigra");
INSERT INTO organism (organism_id,organism_name) VALUES (14,"Oryza sativa");
INSERT INTO organism (organism_id,organism_name) VALUES (15,"Gallus gallus");
INSERT INTO organism (organism_id,organism_name) VALUES (30,"Thellungiella");
INSERT INTO organism (organism_id,organism_name) VALUES (31,"Rosa chinensis");
INSERT INTO organism (organism_id,organism_name) VALUES (32,"Rosa gallica");
INSERT INTO organism (organism_id,organism_name) VALUES (17,"Homo sapiens");
INSERT INTO organism (organism_id,organism_name) VALUES (11,"Helianthus");
INSERT INTO organism (organism_id,organism_name) VALUES (33,"Gossypium");
INSERT INTO organism (organism_id,organism_name) VALUES (24,"Populus sp");
INSERT INTO organism (organism_id,organism_name) VALUES (25,"Rosa");
INSERT INTO organism (organism_id,organism_name) VALUES (26,"Rosa wichurana ");
INSERT INTO organism (organism_id,organism_name) VALUES (27,"Rosa hybrida ");
INSERT INTO organism (organism_id,organism_name) VALUES (13,"Medicago truncatula");
INSERT INTO organism (organism_id,organism_name) VALUES (16,"Vitis vinifera");
INSERT INTO organism (organism_id,organism_name) VALUES (34,"Helianthus annuus");
INSERT INTO organism (organism_id,organism_name) VALUES (35,"Brachypodium");
INSERT INTO organism (organism_id,organism_name) VALUES (36,"Brassica");
INSERT INTO organism (organism_id,organism_name) VALUES (37,"Pisum sativum L");
INSERT INTO organism (organism_id,organism_name) VALUES (38,"Solanum lycopersicum");
INSERT INTO organism (organism_id,organism_name) VALUES (39,"Physcomitrella patens");
INSERT INTO organism (organism_id,organism_name) VALUES (40,"Maize");
INSERT INTO organism (organism_id,organism_name) VALUES (41,"Populus nigra");
INSERT INTO organism (organism_id,organism_name) VALUES (42,"Hevea");
INSERT INTO organism (organism_id,organism_name) VALUES (43,"Barley");
INSERT INTO organism (organism_id,organism_name) VALUES (44,"Wheat");
INSERT INTO organism (organism_id,organism_name) VALUES (45,"Citrus sinensis");
INSERT INTO organism (organism_id,organism_name) VALUES (46,"Epipactis helleborine");
INSERT INTO organism (organism_id,organism_name) VALUES (47,"Cephalanthera damasonium");
INSERT INTO organism (organism_id,organism_name) VALUES (48,"Epipactis purpurata");
INSERT INTO organism (organism_id,organism_name) VALUES (49,"Barley_Hordeum vulgare");
INSERT INTO organism (organism_id,organism_name) VALUES (50,"Brassica Oleracea");
INSERT INTO organism (organism_id,organism_name) VALUES (51,"Medicago sativa");
